from __future__ import annotations

from datetime import date, datetime, timedelta, timezone

from app.security import hash_password

DEMO_PASSWORD = 'Password123!'


def build_demo_data() -> dict:
    now = datetime.now(timezone.utc)
    users = [
        {
            'id': 'user-admin',
            'name': 'Ama Mensah',
            'email': 'admin@bissaesse.com',
            'role': 'admin',
            'title': 'CRM Director',
            'region': 'Global',
            'password_hash': hash_password(DEMO_PASSWORD),
            'created_at': now,
        },
        {
            'id': 'user-manager',
            'name': 'Kojo Boateng',
            'email': 'manager@bissaesse.com',
            'role': 'manager',
            'title': 'Regional Sales Manager',
            'region': 'West Africa',
            'password_hash': hash_password(DEMO_PASSWORD),
            'created_at': now,
        },
        {
            'id': 'user-rep',
            'name': 'Efua Owusu',
            'email': 'rep@bissaesse.com',
            'role': 'sales_rep',
            'title': 'Enterprise Account Executive',
            'region': 'EMEA',
            'password_hash': hash_password(DEMO_PASSWORD),
            'created_at': now,
        },
    ]

    customers = [
        {
            'id': 'cust-aurora',
            'company_name': 'Aurora Manufacturing Group',
            'primary_contact': 'James Attoh',
            'email': 'james@auroramfg.com',
            'phone': '+233-20-555-0101',
            'address': 'Airport City, Accra, Ghana',
            'industry': 'Manufacturing',
            'segment': 'Enterprise',
            'status': 'Active',
            'health_score': 91,
            'annual_revenue': 2400000,
            'employee_count': 520,
            'notes': 'Key account for equipment modernization programme.',
            'owner_id': 'user-manager',
            'owner_name': 'Kojo Boateng',
            'history': [
                {'timestamp': now - timedelta(days=21), 'channel': 'Meeting', 'summary': 'Quarterly business review completed.', 'owner_name': 'Kojo Boateng'},
                {'timestamp': now - timedelta(days=7), 'channel': 'Call', 'summary': 'Confirmed expansion budget for Q4 rollout.', 'owner_name': 'Efua Owusu'},
            ],
            'created_at': now - timedelta(days=120),
            'updated_at': now - timedelta(days=7),
        },
        {
            'id': 'cust-kingsway',
            'company_name': 'Kingsway Logistics',
            'primary_contact': 'Linda Biney',
            'email': 'linda@kingswaylogistics.com',
            'phone': '+233-20-555-0102',
            'address': 'Tema Port, Tema, Ghana',
            'industry': 'Logistics',
            'segment': 'Enterprise',
            'status': 'Onboarding',
            'health_score': 78,
            'annual_revenue': 1800000,
            'employee_count': 320,
            'notes': 'Transitioning from legacy CRM vendor.',
            'owner_id': 'user-rep',
            'owner_name': 'Efua Owusu',
            'history': [
                {'timestamp': now - timedelta(days=30), 'channel': 'Email', 'summary': 'Shared onboarding checklist and security documents.', 'owner_name': 'Efua Owusu'},
            ],
            'created_at': now - timedelta(days=90),
            'updated_at': now - timedelta(days=3),
        },
        {
            'id': 'cust-nova',
            'company_name': 'Nova Health Systems',
            'primary_contact': 'Dr. Safia Musa',
            'email': 'safia@novahealth.com',
            'phone': '+233-20-555-0103',
            'address': 'Ridge, Accra, Ghana',
            'industry': 'Healthcare',
            'segment': 'Mid-Market',
            'status': 'Lead',
            'health_score': 64,
            'annual_revenue': 920000,
            'employee_count': 140,
            'notes': 'Evaluating CRM and customer support automation bundle.',
            'owner_id': 'user-manager',
            'owner_name': 'Kojo Boateng',
            'history': [
                {'timestamp': now - timedelta(days=10), 'channel': 'Meeting', 'summary': 'Initial requirements workshop held with operations leadership.', 'owner_name': 'Kojo Boateng'},
            ],
            'created_at': now - timedelta(days=55),
            'updated_at': now - timedelta(days=2),
        },
        {
            'id': 'cust-savannah',
            'company_name': 'Savannah Retail Collective',
            'primary_contact': 'Yaa Nkrumah',
            'email': 'yaa@savannahretail.com',
            'phone': '+233-20-555-0104',
            'address': 'Kumasi Central, Kumasi, Ghana',
            'industry': 'Retail',
            'segment': 'SMB',
            'status': 'At Risk',
            'health_score': 52,
            'annual_revenue': 410000,
            'employee_count': 48,
            'notes': 'Needs executive attention after delayed user adoption.',
            'owner_id': 'user-rep',
            'owner_name': 'Efua Owusu',
            'history': [
                {'timestamp': now - timedelta(days=5), 'channel': 'Note', 'summary': 'Requested tailored adoption plan and retraining calendar.', 'owner_name': 'Efua Owusu'},
            ],
            'created_at': now - timedelta(days=180),
            'updated_at': now - timedelta(days=1),
        },
        {
            'id': 'cust-atlas',
            'company_name': 'Atlas Energy Partners',
            'primary_contact': 'Michael Quaye',
            'email': 'michael@atlasenergy.com',
            'phone': '+233-20-555-0105',
            'address': 'Takoradi Harbour, Takoradi, Ghana',
            'industry': 'Energy',
            'segment': 'Enterprise',
            'status': 'Active',
            'health_score': 88,
            'annual_revenue': 3200000,
            'employee_count': 680,
            'notes': 'Strong upsell opportunity for field service visibility dashboards.',
            'owner_id': 'user-admin',
            'owner_name': 'Ama Mensah',
            'history': [
                {'timestamp': now - timedelta(days=15), 'channel': 'Call', 'summary': 'Reviewed field service dashboard adoption metrics.', 'owner_name': 'Ama Mensah'},
            ],
            'created_at': now - timedelta(days=200),
            'updated_at': now - timedelta(days=4),
        },
        {
            'id': 'cust-palmline',
            'company_name': 'Palmline Foods Export',
            'primary_contact': 'Abena Larbi',
            'email': 'abena@palmlinefoods.com',
            'phone': '+233-20-555-0106',
            'address': 'Spintex Road, Accra, Ghana',
            'industry': 'Food & Beverage',
            'segment': 'Mid-Market',
            'status': 'Lead',
            'health_score': 70,
            'annual_revenue': 760000,
            'employee_count': 92,
            'notes': 'Interested in export customer lifecycle automation.',
            'owner_id': 'user-manager',
            'owner_name': 'Kojo Boateng',
            'history': [
                {'timestamp': now - timedelta(days=8), 'channel': 'Email', 'summary': 'Sent proposal summary and implementation timeline.', 'owner_name': 'Kojo Boateng'},
            ],
            'created_at': now - timedelta(days=40),
            'updated_at': now - timedelta(days=2),
        },
    ]

    deals = [
        {
            'id': 'deal-aurora-renewal',
            'title': 'Aurora multi-site renewal',
            'customer_id': 'cust-aurora',
            'customer_name': 'Aurora Manufacturing Group',
            'owner_id': 'user-manager',
            'owner_name': 'Kojo Boateng',
            'stage': 'Negotiation',
            'value': 450000,
            'probability': 80,
            'expected_close_date': date.today() + timedelta(days=25),
            'description': 'Renewal plus analytics expansion for six regional plants.',
            'history': [
                {'timestamp': now - timedelta(days=12), 'stage': 'Proposal', 'note': 'Submitted revised rollout proposal.', 'probability': 65},
                {'timestamp': now - timedelta(days=4), 'stage': 'Negotiation', 'note': 'Commercial review with procurement in progress.', 'probability': 80},
            ],
            'created_at': now - timedelta(days=30),
            'updated_at': now - timedelta(days=4),
        },
        {
            'id': 'deal-kingsway-launch',
            'title': 'Kingsway onboarding expansion',
            'customer_id': 'cust-kingsway',
            'customer_name': 'Kingsway Logistics',
            'owner_id': 'user-rep',
            'owner_name': 'Efua Owusu',
            'stage': 'Proposal',
            'value': 220000,
            'probability': 60,
            'expected_close_date': date.today() + timedelta(days=45),
            'description': 'Add warehouse automation workflows to the original onboarding scope.',
            'history': [
                {'timestamp': now - timedelta(days=6), 'stage': 'Qualification', 'note': 'Validated warehouse use cases and approval chain.', 'probability': 45},
                {'timestamp': now - timedelta(days=2), 'stage': 'Proposal', 'note': 'Shared commercial proposal with logistics team.', 'probability': 60},
            ],
            'created_at': now - timedelta(days=20),
            'updated_at': now - timedelta(days=2),
        },
        {
            'id': 'deal-nova-ai',
            'title': 'Nova patient outreach pilot',
            'customer_id': 'cust-nova',
            'customer_name': 'Nova Health Systems',
            'owner_id': 'user-manager',
            'owner_name': 'Kojo Boateng',
            'stage': 'Qualification',
            'value': 180000,
            'probability': 35,
            'expected_close_date': date.today() + timedelta(days=60),
            'description': 'Pilot for patient engagement and retention analytics.',
            'history': [
                {'timestamp': now - timedelta(days=5), 'stage': 'Prospecting', 'note': 'Opportunity opened after requirements workshop.', 'probability': 20},
                {'timestamp': now - timedelta(days=1), 'stage': 'Qualification', 'note': 'Security and compliance review scheduled.', 'probability': 35},
            ],
            'created_at': now - timedelta(days=8),
            'updated_at': now - timedelta(days=1),
        },
        {
            'id': 'deal-atlas-forecast',
            'title': 'Atlas field service analytics',
            'customer_id': 'cust-atlas',
            'customer_name': 'Atlas Energy Partners',
            'owner_id': 'user-admin',
            'owner_name': 'Ama Mensah',
            'stage': 'Closed Won',
            'value': 610000,
            'probability': 100,
            'expected_close_date': date.today() - timedelta(days=8),
            'description': 'Won strategic expansion for field service analytics and alerts.',
            'history': [
                {'timestamp': now - timedelta(days=18), 'stage': 'Negotiation', 'note': 'Executive alignment secured.', 'probability': 90},
                {'timestamp': now - timedelta(days=8), 'stage': 'Closed Won', 'note': 'Signed master services agreement.', 'probability': 100},
            ],
            'created_at': now - timedelta(days=50),
            'updated_at': now - timedelta(days=8),
        },
        {
            'id': 'deal-savannah-rescue',
            'title': 'Savannah adoption rescue package',
            'customer_id': 'cust-savannah',
            'customer_name': 'Savannah Retail Collective',
            'owner_id': 'user-rep',
            'owner_name': 'Efua Owusu',
            'stage': 'Prospecting',
            'value': 65000,
            'probability': 25,
            'expected_close_date': date.today() + timedelta(days=20),
            'description': 'Consulting engagement to improve adoption and retention.',
            'history': [
                {'timestamp': now - timedelta(days=3), 'stage': 'Prospecting', 'note': 'Recovery offer drafted for customer success review.', 'probability': 25},
            ],
            'created_at': now - timedelta(days=3),
            'updated_at': now - timedelta(days=3),
        },
        {
            'id': 'deal-palmline-upgrade',
            'title': 'Palmline exporter growth package',
            'customer_id': 'cust-palmline',
            'customer_name': 'Palmline Foods Export',
            'owner_id': 'user-manager',
            'owner_name': 'Kojo Boateng',
            'stage': 'Closed Lost',
            'value': 140000,
            'probability': 0,
            'expected_close_date': date.today() - timedelta(days=16),
            'description': 'Lost to incumbent ERP vendor bundling limited CRM capabilities.',
            'history': [
                {'timestamp': now - timedelta(days=16), 'stage': 'Closed Lost', 'note': 'Budget frozen for current fiscal year.', 'probability': 0},
            ],
            'created_at': now - timedelta(days=35),
            'updated_at': now - timedelta(days=16),
        },
    ]

    activities = [
        {
            'id': 'act-1',
            'title': 'Prepare renewal redlines',
            'activity_type': 'Task',
            'customer_id': 'cust-aurora',
            'customer_name': 'Aurora Manufacturing Group',
            'assigned_to_id': 'user-manager',
            'assigned_to_name': 'Kojo Boateng',
            'priority': 'High',
            'due_date': now + timedelta(days=2),
            'status': 'Pending',
            'deal_id': 'deal-aurora-renewal',
            'notes': 'Coordinate commercial redlines with procurement and legal.',
            'completed_at': None,
            'created_at': now - timedelta(days=1),
            'updated_at': now - timedelta(days=1),
        },
        {
            'id': 'act-2',
            'title': 'Warehouse rollout discovery call',
            'activity_type': 'Call',
            'customer_id': 'cust-kingsway',
            'customer_name': 'Kingsway Logistics',
            'assigned_to_id': 'user-rep',
            'assigned_to_name': 'Efua Owusu',
            'priority': 'Medium',
            'due_date': now + timedelta(days=1),
            'status': 'Pending',
            'deal_id': 'deal-kingsway-launch',
            'notes': 'Confirm training needs for warehouse managers.',
            'completed_at': None,
            'created_at': now - timedelta(days=2),
            'updated_at': now - timedelta(days=2),
        },
        {
            'id': 'act-3',
            'title': 'Nova security questionnaire review',
            'activity_type': 'Meeting',
            'customer_id': 'cust-nova',
            'customer_name': 'Nova Health Systems',
            'assigned_to_id': 'user-manager',
            'assigned_to_name': 'Kojo Boateng',
            'priority': 'Critical',
            'due_date': now + timedelta(days=5),
            'status': 'Pending',
            'deal_id': 'deal-nova-ai',
            'notes': 'Review compliance requirements with IT and legal.',
            'completed_at': None,
            'created_at': now - timedelta(days=1),
            'updated_at': now - timedelta(days=1),
        },
        {
            'id': 'act-4',
            'title': 'Atlas executive adoption report',
            'activity_type': 'Email',
            'customer_id': 'cust-atlas',
            'customer_name': 'Atlas Energy Partners',
            'assigned_to_id': 'user-admin',
            'assigned_to_name': 'Ama Mensah',
            'priority': 'High',
            'due_date': now - timedelta(days=1),
            'status': 'Pending',
            'deal_id': 'deal-atlas-forecast',
            'notes': 'Share QBR-ready summary with COO and PMO leads.',
            'completed_at': None,
            'created_at': now - timedelta(days=4),
            'updated_at': now - timedelta(days=4),
        },
        {
            'id': 'act-5',
            'title': 'Savannah retraining follow-up',
            'activity_type': 'Meeting',
            'customer_id': 'cust-savannah',
            'customer_name': 'Savannah Retail Collective',
            'assigned_to_id': 'user-rep',
            'assigned_to_name': 'Efua Owusu',
            'priority': 'High',
            'due_date': now + timedelta(days=4),
            'status': 'Completed',
            'deal_id': 'deal-savannah-rescue',
            'notes': 'Customer success retraining plan approved.',
            'completed_at': now - timedelta(hours=12),
            'created_at': now - timedelta(days=3),
            'updated_at': now - timedelta(hours=12),
        },
        {
            'id': 'act-6',
            'title': 'Palmline churn debrief',
            'activity_type': 'Note',
            'customer_id': 'cust-palmline',
            'customer_name': 'Palmline Foods Export',
            'assigned_to_id': 'user-manager',
            'assigned_to_name': 'Kojo Boateng',
            'priority': 'Low',
            'due_date': now - timedelta(days=10),
            'status': 'Completed',
            'deal_id': 'deal-palmline-upgrade',
            'notes': 'Captured loss reasons and competitive intelligence.',
            'completed_at': now - timedelta(days=10),
            'created_at': now - timedelta(days=10),
            'updated_at': now - timedelta(days=10),
        },
    ]

    return {'users': users, 'customers': customers, 'deals': deals, 'activities': activities}
